export { default as Hero } from "./Hero";
export { default as Gallery } from "./Gallery";
export { default as Explore } from "./Explore";
export { default as Inspiration } from "./Inspiration";
export { default as Navbar } from "./Navbar";
export { default as PopularCollection } from "./PopularCollection";
export { default as Services } from "./Services";
export { default as Spaces } from "./Spaces";
export { default as Footer } from "./Footer";
